/* eslint-disable max-len */
import { constants } from './common';

export const Constants = {
    ...constants,
    urlDateFormat: 'YYYY-MM-DD',
    londonTz: 'Europe/London',
    SELECTED_BOOKMAKER_COOKIE: 'selected_bookmaker',
    RACE_INDEX_FILTERS_COOKIE: 'race_index_filters',
    BET_HISTORY_STORAGE_ITEM: 'bet_history_storage_item',
    RUNNER_RACES_TYPES: {
        RECENT: 'RECENT',
        SUBSEQUENT: 'SUBSEQUENT',
    },
    ANALYTICS_LOCATIONS: {
        BETSLIP: 'Betslip',
        MY_RACING_POST: 'My Racing Post',
        MY_BOOKMAKERS: 'My Bookmakers',
    },
    ODDS_TYPES: {
        FRACTIONAL: 'fractional',
        DECIMAL: 'decimal',
    },
    LOGIN_TYPES: {
        FORM: 'form',
        IFRAME: 'iframe',
        WINDOW: 'window',
    },
    BET_TYPE_NAMES: {
        Single: 'single',
        Double: 'double',
        Treble: 'treble',
        Trixie: 'trixie',
        Patent: 'patent',
        '4-fold': 'accumulator-4',
        '5-fold': 'accumulator-5',
        '6-fold': 'accumulator-6',
        '7-fold': 'accumulator-7',
        '8-fold': 'accumulator-8',
        '9-fold': 'accumulator-9',
        '10-fold': 'accumulator-10',
        Yankee: 'yankee',
        'Lucky 15': 'lucky-15',
        Canadian: 'canadian',
        'Lucky 31': 'lucky-31',
        'Lucky 63': 'lucky-63',
        Heinz: 'heinz',
        'Super Heinz': 'super-heinz',
        Goliath: 'goliath',
        Forecast: 'straight-forecast',
        'Reverse Forecast': 'reverse-forecast',
        Tricast: 'straight-tricast',
        'Combination Tricast': 'combination-tricast',
        'Combination Forecast': 'combination-forecast',
    },
    MULTIPLE_BET_TYPES_DESC: {
        double: `A Double consists of 1 bet on 2 selections from different races.${'\n'}Both must be successful to get a return.`,
        treble: `A Treble consists of 1 bet on 3 selections from different races.${'\n'}All must be successful to get a return`,
        trixie: `A Trixie consists of 4 bets involving 3 selections from different races. ”3 Double bets & 1 Treble bet”${'\n'}A minimum of 2 successful selections will guarantee a return.`,
        patent: `A Patent consists of 7 bets involving 3 selections from different races. ”3 Single bets, 3 Double bets & 1 Treble bet.”${'\n'}Just one successful selection will guarantee a return.`,
        yankee: `A Yankee consists of 11 bets involving 4 selections from different races. ”6 Double bets, 4 Treble bets & 1 Fourfold Accumulator.”${'\n'}A minimum of 2 successful selections will guarantee a return`,
        'lucky-15': `A Lucky 15 consists of 15 bets involving 4 selections from different races. ”4 Single bets, 6 Double bets, 4 Treble bets & 1 Fourfold Accumulator.”${'\n'}Just one successful selections will guarantee a return.`,
        canadian: `A Canadian consists of 26 bets involving 5 selections from different races. ”10 Double bets, 10 Treble bets, 5 Fourfold Accumulator bets & 1 Fivefold Accumulator.”${'\n'}A mimimum of 2 successful selections will guarantee a return.`,
        'lucky-31': `A Lucky 31 consists of 31 bets involving 5 selections from different races. ”5 Single bets, 10 Double bets, 10 Treble bets, 5 Fourfold Accumulator bets & 1 Fivefold Accumulator”.${'\n'}Just one successful selection will guarantee a return.`,
        heinz: `A Heinz consists of 57 bets involving 6 selections from different races. ”15 Double bets, 20 Treble bets, 15 Fourfold Accumulators, 6 Fivefold Accumulator bets & 1 Sixfold Accumulator”.${'\n'}A minimum of 2 successful selections will guarantee a return.`,
        'lucky-63': `A Lucky 63 consists of 63 bets involving six selections from different races. ”6 Single bets, 15 Double bets, 20 Treble bets, 15 Fourfold Accumulator bets, 6 Fivefold Accumulator bets & 1 Sixfold Accumulator.”${'\n'}Just one successful selection will guarantee a return.`,
        'super-heinz': `A Super Heinz consists of 120 bets involving seven selections from different races. ”21 Double bets, 35 Treble bets, 35 Fourfold Accumulator bets, 21 Fivefold Accumulator bets, 7 Sixfold Accumulator bets & 1 Sevenfold Accumulator.”${'\n'}A minimum of 2 successful selections will guarantee a return.`,
        goliath: `A Goliath consists of 247 bets involving eight selections from eight different races. ”28 Double bets, 56 Treble bets, 70 Fourfold Accumulator bets, 56 Fivefold Accumulator bets, 28 Sixfold Accumulator bets, 8 Sevenfold Accumulator bets & 1 Eightfold Accumulator.”${'\n'}A minimum of 2 successful selections will guarantee a return.`,
        accumulator: `An Accumulator consists of 1 bet involving 4 or more selections from different races.${'\n'}All selections must be successful to guarantee a return`,
    },
    PAGES: {
        RACECARDS: '/racecards',
        RESULTS: '/racing-results',
        TODAY: '/today',
        RP1_RESULTS: '/results',
        RP1_FAST_RESULTS: '/fast-results',
    },
    // Need to think of a way of exporting it from the CL
    DEFAULT_RACE_INDEX_FILTERS: {
        date: '', // Will be set to current date when getRaceCards saga is used
        raceStatus: constants.RACE_FILTERS.RACE_STATUS.ALL, // Possible values ALL, RACES, RESULTS
        courses: [], // Possible values empty array or array with courseIds
        raceType: constants.RACE_FILTERS.RACE_TYPE.ALL, // Possible values ALL, FLAT, JUMPS
        isHandicap: constants.RACE_FILTERS.HANDICAP.IS_NOT_HANDICAP, // Possible values true or false
    },
    BET_TYPE_STRAIGHT_TRICASTS_FORECASTS: [
        'Forecast',
        'Tricast',
    ],
    BET_TYPE_TRICASTS_FORECASTS: [
        'Forecast',
        'Tricast',
        'Reverse Forecast',
        'Combination Tricast',
        'Combination Forecast',
    ],
    COLLECTION_TYPES: {
        HERO_3_ARTICLES: 'hero3Articles',
        STANDART: 'Standart',
        TIPS_AND_NAPS: 'Tips and Naps collection',
        FEATURES: 'Features Collection',
    },
    DATE_FORMATS: {
        DD_MMMM_YYYY: 'DD MMMM YYYY',
        DD_MMM_YYYY: 'DD MMM YYYY',
        D_MMM_YYYY: 'D MMM YYYY',
        MMMM_DD: 'MMMM DD',
        dddd_D_MMMM: 'dddd D MMMM',
        'YYYY-MM-DD': 'YYYY-MM-DD',
        'DD/MM/YYYY': 'DD/MM/YYYY',
    },
    COUNTRY_CODES: {
        FRA: 'FRA',
        GB: 'GB',
        IRE: 'IRE',
        USA: 'USA',
    },
    RACE_STATUSES: {
        DECLARED: 'declared',
        FAST_RESULT: 'fast result',
        NEXT_OFF: 'next-off',
        RESULT: 'result',
        VOID: 'void',
        CALENDAR: 'calendar',
        NOW: 'now',
    },
    BOOKMAKER_NAMES: {
        SKYBET: 'skybet',
        CORAL: 'coral',
        LADB: 'ladbrokes',
        PADDYPOWER: 'paddypower',
        BETFAIR: 'betfair',
        WH_OXI: 'williamhill',
        BET365_UAT: 'bet365',
        BETWAY: 'betway',
    },
    BOOKMAKER_DISPLAY_NAMES: {
        SURREY: 'Skybet',
        CORAL: 'Coral',
        LADB: 'Ladbrokes',
        PADDYPOWER: 'Paddy Power',
        BETFAIR: 'Betfair',
        WH_OXI: 'William Hill',
        BET365_UAT: 'Bet 365',
        BETWAY: 'Betway',
        BESTODDS: 'Best Odds',
    },
    RACE_TYPES: {
        FLAT: 'Flat',
        JUMPS: 'Jumps',
    },
    RESULT_STATUSES: {
        OPEN: 'Open',
        WON: 'Won',
        VOID: 'Void',
        LOST: 'Lost',
        PLACED: 'Placed',
    },
    RUNNER_INFO: {
        STANDARD: 'standard',
        EXTENDED: 'extended',
    },
    BREAKPOINTS: {
        MOBILE: 'mobile',
        DESKTOP: 'desktop',
        TABLET: 'tablet',
    },
    PAGE_NAMES: {
        ACCOUNTS: 'Accounts',
        BLOODSTOCK_INDEX: 'Bloodstock Index',
        BOOKMAKER_ACCOUNT: 'Bookmaker Account',
        ERROR_PAGE: 'Error Page',
        HOME: 'Home',
        HORSE_PROFILE: 'Horse Profile',
        MY_BETS: 'My Bets',
        NEWS_INDEX: 'News Index',
        RACECARD: 'Racecard',
        RACECARDS_INDEX: 'Racecards Index',
        RESULT: 'Result',
        RESULTS_INDEX: 'Results Index',
        TIPPING_INDEX: 'Tipping Index',
        TODAYS_INDEX: 'Today\'s Index',
    },
    MENU_NAMES: {
        NEWS_SUB_MENU: 'News Sub Menu',
        FOOTER_MENU: 'Footer menu',
    },
    RACECARD_TAB_URL: {
        AT_A_GLANCE: 'at-a-glance',
        COMPARE_ODDS: 'compare-odds',
    },
    RACE_MATRIX_PAGE_SIZES: {
        PAGE_SIZE_TABLET: 5,
        PAGE_SIZE_SMALL_DESKTOP: 4,
        PAGE_SIZE_LARGE_DESKTOP: 7,
    },
    TAXONOMY_COLLECTION_SORT_BY: {
        PUBLISHED_AT: 'published_at',
        UPDATED_AT: 'updated_at',
    },
    ORDER_POSITION: {
        ASC: 'asc',
        DESC: 'desc',
    },
    TAXONOMY_COLLECTION_TYPES: {
        PREVIEWS: 'previews',
        TEN_ARTICLES: '10Articles',
        FOUR_ARTICLES: '4Articles',
        REPORTS: 'reports',
        FEATURES: 'features',
    },
    ARTICLE_TYPES: {
        PREVIEWS_REPORTS: 'Previews/Reports',
    },
    PAGE_META: {
        INDEX: {
            TITLE: 'Horse Racing Cards, Results & Betting | Racing Post',
            META_DESCRIPTION: 'Racing Post, the home of horse racing news, cards and results. Get expert racing tips, form and analysis. Explore our jockey, trainer and horse profiles.',
        },
    },
    RACE_INDEX: {
        RACES_COUNT: 4,
        RACES_COUNT_LARGE_DESKTOP: 5,
    },
    HYBRID_LINKS: {
        ALL_RACES_UPCOMING: '/racecards/time-order/',
        ALL_RACES_TODAY: '/racecards/',
        ALL_RACES_TOMORROW: '/racecards/tomorrow/',
        ALL_RESULTS: '/results/',
    },
    RACECARDS_TABS: {
        FREE: 'free',
        PRO: 'pro',
        AT_A_GLANCE: 'at-a-glance',
        ODDS_COMPARISON: 'odds-comparison',
        LIVE: 'raceday-live',
    },
    GLIDE_CONTENT_PANEL_IDENTIFIERS: {
        QUOTE: 'quote',
    },
}
